[General]
background=
backgroundFillMode=preserveAspectCrop
font=Roboto
fontPixelSize=14
basicTextColor=#e6e0ff
inputBackgroundColor=#1a0a3f
inputTextColor=#e6e0ff
inputBorderColor=#7c4dff
buttonBackgroundColor=#100747
buttonTextColor=#c39bff
buttonHoverColor=#a26bff
warningColor=#ffb020
errorColor=#ff4757
