# SIMURA OS — Calamares displaymanager module.
# Tells Calamares to configure SDDM as the default display manager and to
# auto-login is OFF by default (SIMURA login screen is the brand surface).

displaymanagers:
  - sddm

basicSetup: false
sysconfigSetup: false

defaultDesktopEnvironment:
    executable: "startplasma-x11"
    desktopFile: "plasma"
