# SIMURA OS — Calamares installer top-level config.
# https://calamares.io/docs/

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:       simura
  module:   shellprocess
  config:   shellprocess.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config@simura
  - grubcfg
  - bootloader
  - packages
  - shellprocess@simura
  - umount
- show:
  - finished

branding: simura

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false

# Calamares emits a "geoip" event for time-zone detection; keep it on.
quit-at-end: false
